### PR TITLE
Remove Python 3.9, add 3.12

### PR DESCRIPTION
**Pull request by olemke**

### CODE REVIEW

**Comment by lkluft** [comment]
If this is merged, we might also issue a new release ;) (even if it is only `0.9.1`). The latest release is already years old, and some of the deprecation warnings in it are becoming errors now.

**Comment by olemke** [comment]
Good point, will do a release after the ARTS workshop.

**Comment by olemke** [comment]
Oh, now I know what you mean. :-) Three weeks waiting with the merge was enough to make the tests fail. :-(

**Comment by lkluft** [comment]
> Good point, will do a release after the ARTS workshop.

Is this still planned? ;) It would be nice to have a `matplotlib==3.9` compatible version of typhon.

For me, it would be fine to have a `0.9.1` release. On the other hand, the latest release is a couple of years old... 🤷‍♂️

**Comment by olemke** [comment]
Oops, yes, of course. :-) I cannot promise it's happening until the end of this week, but will release 0.10 soon.

**Pull request merged**
