### PR TITLE
Add trees.py module

### PR DESCRIPTION
**Pull request by JohnMrziglod**
Afaik, there is no implementation of an interval tree in the standard or quasi-standard libraries (numpy, scipy, pandas) of python that can handle overlapping intervals (pandas.Series can only handle non-overlapping intervals).

This IntervalTree class might be very useful if one wants to find overlaps between 100k+ intervals.

### CODE REVIEW

**Review by lkluft — CHANGES_REQUESTED** [review]
Looks good!

Could you please add the module to the docs? A basic structure (as for instance in `docs/typhon.atmosphere.rst`) should be fine. Just add it to Miscellaneous in the `modules.rst`. Thanks!

**Comment by olemke** [comment]
How about copyright? Is this implementation completely written by you?

**Comment by JohnMrziglod** [comment]
It is completely written by me but inspired by a GitHub repository which is under the GNU GPL license (https://github.com/tylerkahn/intervaltree-python). I put a link in the docstring of the class.

**Review by lkluft — APPROVED** [review]

**Comment by olemke** [comment]
Please also check your code style that it roughly follows [our style guide](http://www.radiativetransfer.org/misc/typhon/doc-trunk/developer.html#coding-style). Especially the line length limit for better readability.

**Pull request merged**
