### PR TITLE
added numba and fix bugs in Calc and CalcSpectra

### PR DESCRIPTION
**Pull request by TakayoshiYamada**

### CODE REVIEW

**Comment by olemke** [comment]
Please do not merge pull requests if the tests are failing. Wait for the tests to complete, fix problems if needed, only then merge the pull request. The missing numba dependency in setup.py was now fixed in PR #114.

**Comment by riclarsson** [comment]
How do I know if a build is passed or not?  The tick was green, I thought
this was enough.

2018-02-06 16:40 GMT+09:00 Oliver Lemke <notifications@github.com>:

**Comment by olemke** [comment]
There is still a read cross next to 15150fe above. Not sure which green tick you saw. The travis tests take a couple of minutes. During that time the status of travis is shown as 'in progress' above the Merge button. You have to wait until they complete to see the green check mark or the red cross.

**Comment by olemke** [comment]
Ok, I know which check mark you saw. The first green checkmark (see attached screenshot) only tells you that there are no merge conflicts. Additionally, you have to wait for the Travis tests to complete:

screen shot 2018-02-06 at 09 15 47

Only when the tests succeed and the second green check mark appears, it's okay to do the merge:

screen shot 2018-02-06 at 09 22 49

**Comment by riclarsson** [comment]
Thanks!  I assumed the other check mark was the correct one.  I will be
careful of this in the future.

2018-02-06 17:25 GMT+09:00 Oliver Lemke <notifications@github.com>:

**Comment by gerritholl** [comment]
NB: for me this has triggered https://github.com/numba/llvmlite/issues/182 . This is not typhons fault but others may encounter the same, but I will need to find a fix before I can use typhon again.

**Comment by gerritholl** [comment]
It looks like getting numba to work on an old system is pretty involved.  llvmlite 0.21 apparently needs at least llvm 5.0, the machine on which I work has 3.4.2.  Installing llvm (new or old versions) apparently needs at least cmake 3.4.3, the machine on which I work has cmake 2.8.12.2.  I've asked the system administrator if a newer cmake is accessible so I don't need to compile my own cmake as well (I haven't tried if I have the dependencies for compiling a newer cmake).

Would it be feasible to isolate the component of typhon that has a numba dependency, so that it can be used on old machines without installing a lot of software external to Python from source?  I might succeed in compiling my own cmake and llvm but there may be others with this problem who might try to avoid that.

**Comment by olemke** [comment]
@gerritholl Have you considered using Anaconda instead of plain pip to avoid the hassle of having to compile all dependencies you need for Python modules manually? Anaconda provides all dependencies pre-compiled and can save you a lot of time setting up an environment. It's not perfect and comes with its own set of issues. But using it for several years  now, I must say that it makes life a lot easier.

**Comment by gerritholl** [comment]
I will install anaconda and see if that resolves the `GLIBCXX_3.4.14 not found` problem.

**Comment by gerritholl** [comment]
Thanks, no problem through anaconda.

**Pull request merged**
